https://www.cnblogs.com/jasonfreak/p/5448385.html

In [5]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()
# print(iris.data)
# print(iris.target)

In [ ]:
from sklearn.feature_selection import VarianceThreshold
VarianceThreshold(threshold=3).fit_transform(iris.data)

In [8]:
from sklearn.feature_selection import SelectKBest
from scipy.stats import pearsonr

In [10]:
X = iris.data
Y = iris.target

In [11]:
map(lambda x:pearsonr(x,Y),X.T)

In [15]:
for i in map(lambda x:pearsonr(x,Y),X.T):
    print(i)

(0.7825612318100813, 2.8904783526141205e-32)
(-0.4266575607811244, 5.2015632551773126e-08)
(0.9490346990083884, 4.201873152963374e-76)
(0.9565473328764029, 4.1553110153181703e-81)


In [23]:
np.array(list(map(lambda x:pearsonr(x,Y),X.T))).T

array([[ 7.82561232e-01, -4.26657561e-01,  9.49034699e-01,
         9.56547333e-01],
       [ 2.89047835e-32,  5.20156326e-08,  4.20187315e-76,
         4.15531102e-81]])

In [28]:
X[:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [30]:
def multivariate_pearsonr(X,y):
    scores,pvalues = [],[]
    for ret in map(lambda x:pearsonr(x,y),X.T):
        scores.append( abs(ret[0]) )
        pvalues.append( ret[1] )
    return (np.array(scores), np.array(pvalues))

In [32]:
temp = multivariate_pearsonr(X,Y)

In [33]:
temp

(array([0.78256123, 0.42665756, 0.9490347 , 0.95654733]),
 array([2.89047835e-32, 5.20156326e-08, 4.20187315e-76, 4.15531102e-81]))

In [ ]:
SelectKBest(score_func=multivariate_pearsonr,k=2).fit_transform(iris.data,iris.target)

In [53]:
from sklearn.feature_selection import chi2

In [ ]:
SelectKBest(chi2,k=2).fit_transform(iris.data,iris.target)

In [55]:
from minepy import MINE

In [56]:
def mic(x,y):
    m = MINE()
    m.compute_score(x,y)
    return (m.mic(),0.5)

In [ ]:
SelectKBest(lambda X, Y: np.array(map(lambda x:mic(x, Y), X.T)).T, k=2).fit_transform(iris.data, iris.target)

In [59]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [ ]:
RFE(estimator=LogisticRegression(),n_features_to_select=2).fit_transform(iris.data,iris.target)