In [12]:
# 导入必要的库
import numpy as np
import matplotlib.pyplot as plt
from itertools import cycle
from sklearn import svm,datasets
from sklearn.metrics import roc_curve,auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize,MultiLabelBinarizer
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
%matplotlib inline

In [3]:
# 加载数据
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [13]:
# 多标签分类
# mb = MultiLabelBinarizer()
# y_train = mb.fit_transform(y_train)

In [4]:
# 标签二值化
y = label_binarize(y,classes=[0,1,2])
print(y[:3])

[[1 0 0]
 [1 0 0]
 [1 0 0]]


In [6]:
# 划分训练集和测试集
# 设置种类
n_classes = y.shape[1]
# 训练模型并预测
random_state = np.random.RandomState(0)
n_samples,n_features = X.shape
# 随机化数据
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.5,random_state=0)

In [7]:
# 训练模型
model = OneVsRestClassifier(svm.SVC(kernel='linear',probability=True,random_state=random_state))
clt = model.fit(X_train,y_train)

In [8]:
# 性能评估
clt.score(X_train,y_train)
clt.score(X_test,y_test)

0.6533333333333333

In [9]:
# 查看预测的各类别情况
# 利用svm的方法decision_function
y_preds_scores = clt.decision_function(X_test)
y_preds_scores[:5]

array([[-3.58459897, -0.3117717 ,  1.78242707],
       [-2.15411929,  1.11394949, -2.393737  ],
       [ 1.89199335, -3.89592195, -6.29685764],
       [-4.52609987, -0.63396965,  1.96065819],
       [ 1.39684192, -1.77722963, -6.26300472]])

In [10]:
np.argmax(clt.decision_function(X_test),axis=1)[:5]

array([2, 1, 0, 2, 0], dtype=int64)

In [11]:
# 利用predict_proba
clt.predict_proba(X_test)[:5]
np.argmax(clt.predict_proba(X_test),axis=1)[:5]

array([2, 1, 0, 2, 0], dtype=int64)