In [2]:
import numpy as np
from scipy.linalg import svd

In [3]:
A = np.array([[1,2],[3,4],[5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
# svd
U,s,V = svd(A)
print(U)
print(s)
print(V)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [5]:
print(np.diag(s))

[[9.52551809 0.        ]
 [0.         0.51430058]]


In [7]:
# 根据SVD重建矩阵
Sigma = np.zeros((A.shape[0],A.shape[1]))
Sigma[:A.shape[1],:A.shape[1]] = np.diag(s)
B = U.dot(Sigma.dot(V))
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
