In [1]:
import numpy as np

In [2]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

In [3]:
a.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [7]:
# agrpartiton:在数组中找到最大的N个元素
array = np.array([10, 7, 4, 3, 2, 2, 5, 9, 0, 4, 6, 0])
index = np.argpartition(array,len(array) - 1)
index

array([ 4, 11,  8,  5, 10,  3,  6,  1,  2,  9,  7,  0], dtype=int64)

In [9]:
# clip:如何使数组中的值保持在一定区间内
array = np.array([10, 7, 4, 3, 2, 2, 5, 9, 0, 4, 6, 0])
print(np.clip(array,2,6))

[6 6 4 3 2 2 5 6 2 4 6 2]


In [10]:
# extract:从数组中提取符合条件的元素
arr = np.arange(10)
condition = np.mod(arr,3) == 0

In [12]:
np.extract(condition,arr)

array([0, 3, 6, 9])

In [13]:
np.extract(((arr > 2) & (arr < 8)),arr)

array([3, 4, 5, 6, 7])

In [14]:
# setdiff1d:如何找到仅在A数组中有而B数组没有的元素
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([3,4,7,6,7,8,11,12,14])
c = np.setdiff1d(a,b)
c

array([1, 2, 5, 9])