https://mp.weixin.qq.com/s/6R1MbTe54xqv4afUQ3dalQ

1. 在 reshape 函数中使用参数-1

2. Argpartition：在数组中找到最大的 N 个元素

In [4]:
import numpy as np
array = np.array([10, 7, 4, 3, 2, 2, 5, 9, 0, 4, 6, 0])
index = np.argpartition(array, -5)[-5:]
np.sort(array[index])

array([ 5,  6,  7,  9, 10])

3. Clip：如何使数组中的值保持在一定区间内

In [5]:
array = np.array([10, 7, 4, 3, 2, 2, 5, 9, 0, 4, 6, 0])
print(np.clip(array,2,6))
array = np.array([10, -1, 4, -3, 2, 2, 5, 9, 0, 4, 6, 0])
print(np.clip(array,2,5))

[6 6 4 3 2 2 5 6 2 4 6 2]
[5 2 4 2 2 2 5 5 2 4 5 2]


4. Extract：从数组中提取符合条件的元素

In [6]:
arr = np.arange(10)
condition = np.mod(arr, 3)==0
np.extract(condition, arr)

array([0, 3, 6, 9])

5. setdiff1d：如何找到仅在 A 数组中有而 B 数组没有的元素

In [8]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([3,4,7,6,7,8,11,12,14])
c = np.setdiff1d(a,b)
c

array([1, 2, 5, 9])