In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.15.0


In [3]:
arr = np.arange(10)

In [4]:
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

##### Alternate method

In [5]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

##### 4.Extract all odd numbers from arr

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

##### 5.Replace all odd numbers in arr with -1

In [8]:
arr[arr % 2 == 1] = -1

In [9]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

##### 6.Replace all odd numbers in arr with -1 without changing arr

In [10]:
arr = np.arange(10)
out = np.where(arr % 2 == 1,-1,arr)

##### 7.How to reshape an array?

In [11]:
arr = np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### 8.How to stack two arrays vertically?

In [13]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
# Method 1
np.concatenate([a,b],axis = 0)
# Method 2 
np.vstack([a,b])
# Method 3  np.r_是按列连接两个矩阵，就是把两矩阵上下相加，要求列数相等。
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

##### 9. How to stack two arrays horizontally?

In [14]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
# Method 1
np.concatenate([a,b],axis = 1)
# Method 2
np.hstack([a,b])
# Method 3 np.c_是按行连接两个矩阵，就是把两矩阵左右相加，要求行数相等。
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

##### 10. How to generate custom sequences in numpy without hardcoding?

In [15]:
# np.repeat:对数组中的元素进行连续重复复制
# np.tile:对整个数组进行复制拼接
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

##### 11. How to get the common items between two python numpy arrays?

In [16]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

##### 12. How to remove from one array those items that exist in another?

In [17]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

##### 13. How to get the positions where elements of two arrays match?

In [18]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

##### 14. How to extract all numbers between a given range from a numpy array?

In [19]:
a = np.arange(15)
# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]
# Method 2
index = np.where(np.logical_and(a>=5,a<=10))
# Method 3
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

##### 15. How to make a python function that handles scalars to work on numpy arrays?

In [21]:
def maxx(x,y):
    if x >= y:
        return x
    else:
        return y
# np.vectorize将函数向量化
pair_max = np.vectorize(maxx,otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

##### 16. How to swap two columns in a 2d numpy array?

In [22]:
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

##### 17. How to swap two rows in a 2d numpy array?

In [23]:
# Input
arr = np.arange(9).reshape(3,3)
# Solution
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

##### 18. How to reverse the rows of a 2D array?

In [24]:
arr = np.arange(9).reshape(3,3)
# -1表示步长
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

##### 19. How to reverse the columns of a 2D array?

In [25]:
# Input
arr = np.arange(9).reshape(3,3)
# Solution
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

##### 20. How to create a 2D array containing random floats between 5 and 10?

In [26]:
# Input
arr = np.arange(9).reshape(3,3)
# Solution Method 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
# print(rand_arr)
# Solution Method 2:
rand_arr = np.random.uniform(5,10, size=(5,3))

###### 21. How to print only 3 decimal places in python numpy array?

In [27]:
rand_arr = np.random.random([5,3])
# np.set_printoptions现在打印小数点个数
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.101, 0.511, 0.575],
       [0.247, 0.746, 0.651],
       [0.737, 0.164, 0.042],
       [0.105, 0.399, 0.266]])